### ISSUE TITLE
Email validation on the frontend 

### ISSUE THREAD

**Issue by adityabisht02** [akhil-aggarwal/cookie#13]
Currently the user can write any anything in the email input field. The email needs to be validated before the user can hit the submit button.
![image](https://user-images.githubusercontent.com/89146189/193393940-3ed5b009-0c6b-471f-8972-8d762ecdba7b.png)

**Comment by adityabisht02** [comment]
I would like to work on this @akhil-aggarwal

**Comment by ajax484** [comment]
I would love to work on this @akhil-aggarwal and it can be implemented using regex

**Comment by akhil-aggarwal** [comment]
Please go ahead.

**Comment by adityabisht02** [comment]
I have made the function for validation how do you want me to display the error message? As an alert maybe?

**Comment by akhil-aggarwal** [comment]
> I have made the function for validation how do you want me to display the error message? As an alert maybe?

Try to use Bootstrap alerts in order to match with UI, instead of simple JavaScript alert.

**Comment by adityabisht02** [comment]
Someone else has already resolved this issue so I am closing it.
