### ISSUE TITLE
Preloader and Favicon - Feature Requested

### ISSUE THREAD

**Issue by Pargat-Dhanjal** [akhil-aggarwal/cookie#14]
**Is your feature request related to a problem? Please describe.**
Lets just say it, Preloader are awesome!

**Describe the solution you'd like**
A sick looking preloader that goes along with the theme of the website.

**Describe alternatives you've considered**
Would also love to add a favicon for the website.

**Additional context**
I would love to contribute more to the open source community as a part of hacktober fest

**Comment by ajax484** [comment]
Please assign me this issue

**Comment by akhil-aggarwal** [comment]
go ahead guys

**Comment by akhil-aggarwal** [comment]
Really nice work done by @Pargat-Dhanjal

**Comment by Pargat-Dhanjal** [comment]
@akhil-aggarwal Thanks : )
