### ISSUE TITLE
adding a logo of cookie at the bottom that if clicked on would return back to the top of the page

### ISSUE THREAD

**Issue by dreymotoh** [akhil-aggarwal/cookie#18]
would allow the user to quickly get back to the top of the page

**Comment by himanshu17-2000** [comment]
I want to work on this issue ,can you please assign it to me

**Comment by jbecker7** [comment]
@akhil-aggarwal What if we add this to every page?

**Comment by akhil-aggarwal** [comment]
Go ahead.

**Comment by akhil-aggarwal** [comment]
Nice Work by @dreymotoh

**Comment by dreymotoh** [comment]
thanks :)
