### ISSUE TITLE
Make an about page for the Cookies demonstration website

### ISSUE THREAD

**Issue by akhil-aggarwal** [akhil-aggarwal/cookie#2]
Make an about page for the cookies demonstration website. Simple HTML page with some heading and data for the headings regarding cookies and about their working are enough. Later on we can add the CSS to the HTML page.

**Comment by soumali28** [comment]
I want to contribute to this issue under hacktoberfest 2022.

**Comment by akhil-aggarwal** [comment]
> I want to contribute to this issue under hacktoberfest 2022.

Please go ahead !

**Comment by lovishprabhakar** [comment]
Can I work on this? @akhil-aggarwal

**Comment by akhil-aggarwal** [comment]
Issue solved by @lovishprabhakar gracefully !
