### ISSUE TITLE
Reset cookie not working

### ISSUE THREAD

**Issue by pacific-prashant** [akhil-aggarwal/cookie#40]
Hey @akhil-aggarwal, I just saw that the reset button is not working. I would like to work on this bug as you can see in the screenshot provided below.

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/83504276/193449934-5c554312-b3cc-49b5-95ad-40a9680b7421.png">
  
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/83504276/193449973-f46d7a14-c7a2-48ff-8137-b77796b5917c.png">

**Comment by akhil-aggarwal** [comment]
Solved by @pacific-prashant
