### ISSUE TITLE
Contributors Page

### ISSUE THREAD

**Issue by Rutuj-Runwal** [akhil-aggarwal/cookie#47]
**Is your feature request related to a problem? Please describe.**
Currently we have a contribute button that when clicks takes us to repository 

**Describe the solution you'd like**
A contributors page that fetches contributors realtime using github api as shown below
It will also have a button to link to repository if someone wants to contribute

![image](https://user-images.githubusercontent.com/59436520/193459540-fd17519f-23e8-4c2b-a8b8-970253087bda.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by Rutuj-Runwal** [comment]
@akhil-aggarwal what are your thoughts on this?

**Comment by akhil-aggarwal** [comment]
You can have a different contributor page. Keep the contribute button as it is and go ahead with a different contributors page.
