### ISSUE TITLE
Fix : HTML elements doesn't take data from cookies once page gets refreshed

### ISSUE THREAD

**Issue by akhil-aggarwal** [akhil-aggarwal/cookie#5]
HTML elements don't take data from cookies once the page gets refreshed, that might be due to reloading of .js file again when the page gets refreshed. Need to fix the issue.

**Comment by ArmoryNode** [comment]
Hi there! I can work on this one.

**Comment by akhil-aggarwal** [comment]
> Hi there! I can work on this one.

Go ahead, I have assigned you to the task.
