### ISSUE TITLE
Footer section in About Page is not at bottom

### ISSUE THREAD

**Issue by SujalSamai** [akhil-aggarwal/cookie#54]
**Describe the bug**
The footer section in About Page is not at the very bottom of the page unlike the Home page, this makes the website look quite inconsistent in design perspective.
**To Reproduce**
1. Go to About Page from Navbar
2. Scroll down to Bottom of the page
3. See error in the footer section

**Expected behavior**
The footer section should be at the very bottom of any page.

**Screenshots**
![image](https://user-images.githubusercontent.com/87236576/193611028-823262eb-f883-458c-84f6-e93f0c3ac8e1.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser : Chrome
 - Version : 106.0.5249.91

**Smartphone (please complete the following information):**
 - Device: Realme GT Master Edition
 - OS: Android 12
 - Browser : Chrome
 - Version : 105.0.5195.79

**Additional context**

**Comment by ArmoryNode** [comment]
I can take care of this one.
