### ISSUE TITLE
Back to top buttom improvement!

### ISSUE THREAD

**Issue by kalashvasaniya** [akhil-aggarwal/cookie#74]
### Concise Description

Looking dull in the website 

### Your Solution

Make a arrow type buttom to go to the top

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/akhil-aggarwal/cookie/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by swapn652** [comment]
Hey, can I work on this?
